plugins {
    id 'java'
}

repositories {
    mavenCentral()

    maven {
        url = 'https://repo.papermc.io/repository/maven-public/'
    }
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:26.2.build.+")

    //testImplementation("com.github.seeseemelk:MockBukkit-v1.21:3.133.0") OLD
    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(26)
    }
}